version: '3.1'

services:
    frontend:
        build:
          context: ./frontend
        ports:
          - "3000:3000"
        networks:
          - web_network
    backend:
        build:
          context: ./backend
        ports:
          - "8000:8000"
        depends_on:
          - frontend
        networks:
          - web_network
    redis:
        image: redis:latest
        ports:
            - "6379:6379"  # Expose the default Redis port
        networks:
            - web_network
    nginx: 
        restart: always 
        image: nginx:latest 
        ports: 
            - "80:80"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
        depends_on:
          - frontend
        links:
          - frontend:frontend
        networks:
          - web_network
networks:
    web_network: 
        driver: bridge