version: '3.1'

services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        networks:
            - web_network
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - redis 
            - db
            - frontend
        networks:
            - web_network
        links:
            - db
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    db: 
        image: postgres
        ports:
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/ 
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - web_network
        restart: always
    redis:
        image: redis:latest
        ports:
            - "6379:6379"  # Expose the default Redis port
        networks:
            - web_network
    nginx: 
        restart: always 
        image: nginx:latest 
        ports: 
            - "80:80"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
        depends_on:
            - frontend
        links:
            - frontend:frontend
        networks:
            - web_network
volumes:
    postgres_data: 
networks:
    web_network: 
        driver: bridge